services:
  _defaults:
    autowire: true

  Lingoda\KameleoonBundle\Kameleoon\:
    resource: '../src/Kameleoon/*'

  Kameleoon\KameleoonClientFactory: ~
  Lingoda\KameleoonBundle\Kameleoon\KameleoonClientFactoryWrapper: ~

  Kameleoon\KameleoonClient:
    factory: [ '@Lingoda\KameleoonBundle\Kameleoon\KameleoonClientFactoryWrapper', createWithConfig ]
    arguments:
      $config: '@Lingoda\KameleoonBundle\Kameleoon\KameleoonConfig'

  Lingoda\KameleoonBundle\Cache\KameleoonCacheWarmer:
    arguments:
      $config: '@Lingoda\KameleoonBundle\Kameleoon\KameleoonConfig'
    tags: [ cache.warmer ]

