name: kameleoon-bundle
permissions: write-all
on: [pull_request, push]
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: cancel
        uses: styfle/cancel-workflow-action@0.9.1

      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.19.0
        with:
          php-version: '8.1'

      - name: composer
        uses: ramsey/composer-install@2.1.0
        with:
          composer-options: "--prefer-dist --classmap-authoritative"

      - name: phpstan-cache
        uses: actions/cache@v3.0.3
        with:
          key: phpstan-${{ github.ref }}-${{ github.sha }}
          path: .phpstan-cache
          restore-keys: |
            phpstan-${{ github.ref }}-
            phpstan-

      - name: phpstan
        run: vendor/bin/phpstan analyze -c ./phpstan.neon

      - name: phpspec
        run: vendor/bin/phpspec run
